// CrossDuel puzzle — 9x9 grid, 15 ACROSS words
// Layout:
//   Rows 0-5: col 4 is black (separator); 4-letter word on left (cols 0-3), 4-letter word on right (cols 5-8)
//   Rows 6-8: 7-letter word spanning cols 0-6; cols 7-8 are black
//
// Word numbers are auto-generated by CrosswordGrid's generateWordNumbers().
// They are computed here using the same algorithm so keys match exactly.

export const puzzles = [
  {
    gridSize: 9,

    blackCells: [
      // Rows 0-5: col 4 separates left/right 4-letter words
      '0,4','1,4','2,4','3,4','4,4','5,4',
      // Rows 6-8: 7-letter words at cols 0-6; cols 7-8 are black
      '6,7','6,8',
      '7,7','7,8',
      '8,7','8,8',
    ],

    // Keys match auto-generated word numbers from CrosswordGrid's generateWordNumbers()
    wordPositions: {
      '1_across':  { row: 0, startCol: 0, length: 4 },   // EPIC
      '5_across':  { row: 0, startCol: 5, length: 4 },   // GAME
      '9_across':  { row: 1, startCol: 0, length: 4 },   // BOLD
      '10_across': { row: 1, startCol: 5, length: 4 },   // STAR
      '11_across': { row: 2, startCol: 0, length: 4 },   // APEX
      '12_across': { row: 2, startCol: 5, length: 4 },   // DUEL
      '13_across': { row: 3, startCol: 0, length: 4 },   // GLOW
      '14_across': { row: 3, startCol: 5, length: 4 },   // ACED
      '15_across': { row: 4, startCol: 0, length: 4 },   // IRON
      '16_across': { row: 4, startCol: 5, length: 4 },   // FIRE
      '17_across': { row: 5, startCol: 0, length: 4 },   // ZONE
      '18_across': { row: 5, startCol: 5, length: 4 },   // WORD
      '19_across': { row: 6, startCol: 0, length: 7 },   // TRIUMPH
      '21_across': { row: 7, startCol: 0, length: 7 },   // MASTERS
      '22_across': { row: 8, startCol: 0, length: 7 },   // ECLIPSE
    },

    clues: {
      '1_across':  'Legendary, awe-inspiring',
      '5_across':  'A competitive activity',
      '9_across':  'Daring and fearless',
      '10_across': 'A luminous celestial body',
      '11_across': 'The highest point',
      '12_across': 'A contest between two',
      '13_across': 'Emit a soft light',
      '14_across': 'Performed perfectly',
      '15_across': 'Strong metal element',
      '16_across': 'Intense heat and flame',
      '17_across': 'Designated area',
      '18_across': 'A unit of language',
      '19_across': 'A great victory',
      '21_across': 'Champions of their craft',
      '22_across': 'To surpass or overshadow',
    },

    answers: {
      '1_across':  'EPIC',
      '5_across':  'GAME',
      '9_across':  'BOLD',
      '10_across': 'STAR',
      '11_across': 'APEX',
      '12_across': 'DUEL',
      '13_across': 'GLOW',
      '14_across': 'ACED',
      '15_across': 'IRON',
      '16_across': 'FIRE',
      '17_across': 'ZONE',
      '18_across': 'WORD',
      '19_across': 'TRIUMPH',
      '21_across': 'MASTERS',
      '22_across': 'ECLIPSE',
    },
  },
];
